name: Linux Cloud Server

'on':
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test Linux
        run: |
          echo "Linux server is running"
          uname -a
